turtlebot3: #namespace
    task_and_robot_environment_name: 'TurtleBot3Navigation-v2'
    ros_ws_abspath: "/home/pronton/catkin_ws"
    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #qlearn parameters
    alpha: 0.1
    gamma: 0.99
    epsilon: 0.9
    epsilon_discount: 0.999
    nepisodes: 100000
    nsteps: 1000
    running_step: 0.06 # Time for each step